ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
      # - id: commitizen-branch
      #   stages: [push]

  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/scientific-python/cookie
    rev: 2024.04.23
    hooks:
      - id: sp-repo-review

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: '^tests\/.*_helper\.py$'
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.4
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.7"
    hooks:
      # Run the linter
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: ["--fix", "--show-fixes"]
      # Run the formatter
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.16.0"
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==24.*]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]
        args: [--prose-wrap=always]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
        files: src
        exclude: ^(src/galax/__init__\.py|src/galax/.*?/__init__\.py)$
        additional_dependencies:
          - pytest

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.3.0"
    hooks:
      - id: codespell
        exclude: ^(notebooks|AUTHORS\.rst)$

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: "v0.18"
    hooks:
      - id: validate-pyproject
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

  - repo: local
    hooks:
      - id: disallow-caps
        name: Disallow improper capitalization
        language: pygrep
        entry: PyBind|Numpy|Cmake|CCache|Github|PyTest
        exclude: .pre-commit-config.yaml
