[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-vcs"]


[project]
authors = [
  { name = "galax maintainers", email = "nstarman@users.noreply.github.com" },
  { name = "Jake Nibauer", email = "jnibauer@princeton.edu" },
  { name = "Adrian Price-Whelan", email = "adrianmpw@gmail.com" },
  { name = "Nathaniel Starkman", email = "nstarman@users.noreply.github.com" },
]
classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering",
  "Typing :: Typed",
]
dependencies = [
  "astropy >= 6.0",
  "beartype >= 0.18",
  "coordinax",
  "diffrax >= 0.5",
  "equinox >=0.11, != 0.11.3",
  "jax >= 0.4, != 0.4.27",
  "jaxlib != 0.4.27",
  "lazy_loader >= 0.4",
  "packaging",  # for optional dependencies
  "quax >= 0.0.3",
  "quaxed >=0.4",
  "typing_extensions >= 4.11",
  "unxt",
]
description = "Galactic Dynamics in Jax."
dynamic = ["version"]
name = "galax"
readme = "README.md"
license.file = "LICENSE"
requires-python = ">=3.11"

[project.optional-dependencies]
# All runtime dependencies
all = ["galax[interop-all]"]
# Interoperability dependencies
interop-all = ["galax[interop-gala]"]
interop-gala = ["gala", "astropy!=6.1.0"]
# TODO: galpy and agama
# Documentation dependencies
docs = [
  "sphinx>=7.0",
  "myst_parser>=0.13",
  "sphinx_copybutton",
  "sphinx_autodoc_typehints",
  "furo>=2023.08.17",
]
# Test dependencies
test = [
  "hypothesis[numpy]",
  "nox",
  "pre-commit",
  "pytest >=6,<8",
  "pytest-cov >=3",
  "pytest-arraydiff",
  "sybil",
]
# Development dependencies
dev = [
  "galax[all]",
  "galax[docs]",
  "galax[test]",
]

[project.urls]
"Bug Tracker" = "https://github.com/GalacticDynamics/galax/issues"
Changelog = "https://github.com/GalacticDynamics/galax/releases"
Discussions = "https://github.com/GalacticDynamics/galax/discussions"
Homepage = "https://github.com/GalacticDynamics/galax"


[tool.hatch]
build.hooks.vcs.version-file = "src/galax/_version.py"
metadata.allow-direct-references = true
version.source = "vcs"

[tool.hatch.envs.default]
dependencies = ["pytest", "pytest-cov"]
features = ["test"]
scripts.test = "pytest {args}"


[tool.pytest.ini_options]
addopts = [
  "-ra",
  "--arraydiff",
  "--showlocals",
  "--strict-markers",
  "--strict-config",
]
filterwarnings = [
  "error",
  "ignore:ast\\.Str is deprecated:DeprecationWarning",
  "ignore:numpy\\.ndarray size changed:RuntimeWarning",
  "ignore:Passing arguments 'a':DeprecationWarning",  # TODO: from diffrax
]
log_cli_level = "INFO"
markers = [
  "slow: marks tests as slow (deselect with '-m \"not slow\"')",
  "serial",
]
minversion = "6.0"
testpaths = ["tests/", "docs", "src/galax"]
xfail_strict = true


[tool.coverage]
run.source = ["galax"]
report.exclude_also = [
  # Have to re-enable the standard pragma
  'pragma: no cover',
  # Ignore type-checking stuff
  'if typing.TYPE_CHECKING:',
  'if TYPE_CHECKING:',
  '\.\.\.',
  # Ignore contents of abstract methods
  '@abc.abstractmethod',
  '@abstractmethod',
]


[tool.mypy]
python_version = "3.11"

disallow_incomplete_defs = true
disallow_untyped_defs = true
exclude = [
  '(^/)docs/',      # docs
  '(^|/)tests/',    # tests
  '^conftest\.py$', # nox test configuration
]
strict = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true

disable_error_code = ["no-redef"]                                            # <- plum multiple dispatch
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]

[[tool.mypy.overrides]]
disable_error_code = ["name-defined"] # <- jaxtyping
module = "galax.*"

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
  "astropy.*",
  "beartype.*",
  "diffrax.*",
  "equinox.*",
  "hypothesis.*",
  "jax.*",
  "jax_cosmo.*",
  "jaxtyping.*",
  "numpy.*",
  "scipy.*",
  "sympy.*",
  "sympy2jax.*",
]


[tool.ruff]
src = ["src"]

[tool.ruff.lint]
extend-select = ["ALL"]
ignore = [
  "ANN101",  # Missing type annotation for self in method
  "ANN102",  # Missing type annotation for cls in classmethod
  "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed in `*args`
  "COM812",  # Missing trailing comma in Python 3.6+
  "D203",    # 1 blank line required before class docstring
  "D105",    # Missing docstring in magic method
  "D107",    # Missing docstring in `__init__`
  "D213",    # Multi-line docstring summary should start at the second line
  "E741",    # Ambiguous variable name
  "F722",    # Syntax error in forward annotation  <- jaxtyping
  "F811",    # Redefinition <- plum multiple dispatch
  "F821",    # undefined name  <- jaxtyping
  "FIX002",  # Line contains TODO, consider resolving the issue
  "ISC001",  # Implicit string concatenation <- ruff-format
  "N80",     # Naming conventions.
  "PD",      # pandas-vet
  "PLC0414", # Import alias does not rename original package
  "PLR",     # Design related pylint codes
  "PYI041",  # Use `float` instead of `int | float` <- beartype is more strict
  "TCH00",   # Move into a type-checking block
  "TD002",   # Missing author in TODO
  "TD003",   # Missing issue link on the line following this TODO
  "UP037",   # Remove quote from type annotation  <- jaxtyping
]
# Uncomment if using a _compat.typing backport
# typing-modules = ["galax._compat.typing"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F403"]
"__init__.pyi" = ["F401", "F403"]
"docs/conf.py" = [
  "A001",   # Variable `copyright` is shadowing a Python builtin
  "INP001", # implicit namespace package
]
"notebooks/**" = ["ANN", "D103", "FBT", "T201"]
"noxfile.py" = ["ERA001", "T20"]
"tests/**" = [
  "ANN",
  "ARG001",
  "ARG002",
  "D10",
  "E731",
  "ERA001", # Found commented-out code  # TODO: remove this
  "FBT001", # Boolean-typed positional argument in a function definition
  "INP001",
  "S101",
  "S301",
  "SLF001",
  "T20",
  "TID252", # Relative imports from parent modules are banned
]

[tool.ruff.lint.flake8-type-checking]
exempt-modules = []

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["quaxed", "unxt", "coordinax"]
known-local-folder = ["galax"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"


[tool.pylint]
ignore-paths = [".*/_version.py"]
messages_control.disable = [
  "design",
  "fixme",
  "import-outside-toplevel",
  "invalid-name",                  # ruff N80*
  "line-too-long",
  "missing-module-docstring",
  "protected-access",              # ruff SLF001
  "unnecessary-ellipsis",
  "unnecessary-lambda-assignment", # ruff E731
  "unnecessary-pass",              # handled by ruff
  "wrong-import-position",
  "wrong-import-order",            # handled by ruff
]
py-version = "3.11"
reports.output-format = "colorized"
similarities.ignore-imports = "yes"
