"""A copy of `galax.coordinates`' phase-space contract, for `Orbit`.

`Orbit` is a `galax.dynamics` type that implements the `galax.coordinates`
phase-space contract, so it must be tested against it. The contract lives in
`galax.coordinates`' own test tree, which after #916 is a different
distribution and not an importable path -- `packages/galax.coordinates`
contains a dot.

This is a deliberate copy, not an import: it keeps each portion's tests
runnable against a standalone install, with no shared test package and nothing
extra shipped in a wheel.

The cost is drift, and it is not policed: if the original gains a requirement
or tightens an existing one, this copy will not follow, and `Orbit` can stop
conforming while these tests still pass. Nothing detects that -- when you
change the contract in `galax.coordinates`' tests, change it here too.

Generated by flattening `tests/unit/coordinates/{test_base.py,
psc/test_base.py, psc/test_base_single.py}`, so a regenerate-and-diff is the
quickest way to see what has diverged.

One edit was made after generating: the two source modules each declare a
TypeVar named `WT` with a different bound, and flattening them put both in one
namespace where the second silently rebound the first. They are `CoordT` and
`BasicCoordT` here. A regenerate will reintroduce the collision -- rename them
again.
"""

from abc import ABCMeta, abstractmethod

from jaxtyping import PRNGKeyArray
from typing import TypeVar

import jax.random as jr
import optype as op
import pytest
from plum import convert

import coordinax as cx
import quaxed.numpy as jnp
import unxt as u
from dataclassish import replace

import galax.coordinates as gc
import galax.coordinates.custom_types as gt


def getkeys(
    num: int, key: PRNGKeyArray | int = 0
) -> tuple[PRNGKeyArray, op.CanIter[PRNGKeyArray]]:
    """Return an iterable of keys."""
    key = jr.key(key) if isinstance(key, int) else key
    newkey, *subkeys = jr.split(key, num=num + 1)
    return newkey, iter(subkeys)


class AbstractPhaseSpaceObject_Test[CT: gc.AbstractPhaseSpaceObject](metaclass=ABCMeta):
    """Abstract base class for testing `galax.coordinates.AbstractPhaseSpaceObject`."""

    #################################################################
    # Fixtures

    @pytest.fixture(
        scope="class",
        params=[gc.frames.simulation_frame],
        ids=lambda param: str(param),
    )
    def frame(self, request: pytest.FixtureRequest) -> cx.frames.AbstractReferenceFrame:
        """Return the frame to test."""
        return request.param

    # ----------------------------------------------------

    @pytest.fixture(scope="class", params=[(10,), (5, 4)], ids=lambda param: str(param))
    def shape(self, request: pytest.FixtureRequest) -> gt.Shape:
        """Return a shape."""
        return request.param

    @pytest.fixture(scope="class")
    @abstractmethod
    def w_cls(self) -> type[CT]:
        """Return the class of a phase-space position."""
        raise NotImplementedError

    @abstractmethod
    def make_w(
        self, w_cls: type[CT], shape: gt.Shape, frame: cx.frames.AbstractReferenceFrame
    ) -> CT:
        """Return a phase-space position."""
        raise NotImplementedError

    @pytest.fixture
    def w(self, w_cls: type[CT], shape: gt.Shape) -> CT:
        """Return a phase-space position."""
        return self.make_w(w_cls, shape)

    #################################################################

    # =========================================================
    # Attributes

    def test_q(self, w: CT, shape: gt.Shape) -> None:
        """Test :attr:`~galax.coordinates.AbstractPhaseSpaceObject.q`."""
        assert hasattr(w, "q")
        assert w.q.shape == shape
        assert len(w.q.components) == 3

    def test_p(self, w: CT, shape: gt.Shape) -> None:
        """Test :attr:`~galax.coordinates.AbstractPhaseSpaceObject.p`."""
        assert hasattr(w, "p")
        assert w.p.shape == w.q.shape
        assert w.p.shape == shape
        assert len(w.p.components) == 3

    def test_frame(self, w: CT, frame: cx.frames.AbstractReferenceFrame) -> None:
        """Test :attr:`~galax.coordinates.AbstractPhaseSpaceObject.frame`."""
        assert hasattr(w, "frame")
        assert w.frame == frame

    # =========================================================
    # Vector API

    def test_data_keys(self, w: CT) -> None:
        """Test :attr:`~galax.coordinates.PhaseSpacePosition.data`."""
        assert isinstance(w.data, cx.KinematicSpace)
        assert "length" in w.data
        assert "speed" in w.data

    def test_uconvert(self, w: CT) -> None:
        """Test :meth:`~galax.coordinates.PhaseSpacePosition.uconvert`."""
        w2 = w.uconvert("solarsystem")
        # TODO: more detailed tests
        assert w2.q.x.unit == "AU"
        assert w2.p.x.unit == "AU/yr"

    # =========================================================
    # Array API

    def test_shape(self, w: CT, shape: gt.Shape) -> None:
        """Test :attr:`~galax.coordinates.AbstractPhaseSpaceObject.shape`."""
        # Check existence
        assert hasattr(w, "shape")

        # Confirm relation to shape_tuple
        assert w.shape == w._shape_tuple[0]

        # Confirm relation to components full shape
        assert w.shape == w.q.shape

        # Confirm from definition
        assert w.shape == shape

    def test_ndim(self, w: CT) -> None:
        """Test :attr:`~galax.coordinates.AbstractPhaseSpaceObject.ndim`."""
        # Check existence
        assert hasattr(w, "ndim")

        # Confirm relation to shape and components
        assert w.ndim == len(w.shape)
        assert w.ndim == w.q.ndim

    def test_len(self, w: CT) -> None:
        """Test :meth:`~galax.coordinates.PhaseSpacePosition.__len__`."""
        # Check existence
        assert hasattr(w, "__len__")

        # Confirm relation to shape and components
        assert len(w) == w.shape[0]
        assert len(w) == w.q.shape[0]

    # def test_getitem()  # TODO: abstract tests

    # =========================================================
    # Python API

    def test_str(self, w: CT) -> None:
        """Test `__str__`."""
        assert isinstance(str(w), str)
        # TODO: more

    # =========================================================
    # Further Array properties

    def test_full_shape(self, w: CT, shape: gt.Shape) -> None:
        """Test :attr:`~galax.coordinates.PhaseSpacePosition.full_shape`."""
        # Definition
        batch_shape, component_shapes = w._shape_tuple
        assert w.full_shape == (*batch_shape, sum(component_shapes))

        # Sanity check
        assert w.full_shape[: len(w.shape)] == w.shape
        assert len(w.full_shape) == len(w.shape) + 1

    # =========================================================

    def test_w(self, w: CT) -> None:
        """Test :meth:`~galax.coordinates.PhaseSpacePosition.w`."""
        # Check existence
        assert hasattr(w, "w")

        # units are not None
        assert w.w(units="galactic").shape[:-1] == w.full_shape[:-1]

    # =========================================================
    # Dynamical properties

    def test_kinetic_energy(self, w: CT) -> None:
        """Test method ``kinetic_energy``."""
        ke = w.kinetic_energy()
        assert ke.shape == w.shape  # confirm relation to shape and components
        assert jnp.all(ke >= u.Q(0, "km2/s2"))
        # TODO: more tests


CoordT = TypeVar("CoordT", bound=gc.AbstractPhaseSpaceCoordinate)


class AbstractPhaseSpaceCoordinate_Test(
    AbstractPhaseSpaceObject_Test[CoordT], metaclass=ABCMeta
):
    """Test :class:`~galax.coordinates.AbstractPhaseSpaceCoordinate`."""

    def make_w(self, w_cls: type[CoordT], shape: gt.Shape) -> CoordT:
        """Return a phase-space position."""
        _, keys = getkeys(3)

        q = u.Q(jr.normal(next(keys), (*shape, 3)), "kpc")
        p = u.Q(jr.normal(next(keys), (*shape, 3)), "km/s")
        t = u.Q(jr.normal(next(keys), shape), "Myr")
        return w_cls(q=q, p=p, t=t, frame=gc.frames.simulation_frame)

    #################################################################

    # =========================================================
    # Attributes

    def test_t(self, w: CoordT) -> None:
        """Test `~galax.coordinates.AbstractPhaseSpaceCoordinate.t`."""
        assert w.t.shape == w.shape
        assert isinstance(w.t, u.Quantity)
        assert u.dimension_of(w.t) == "time"

    # =========================================================
    # Coordinate API

    def test_dimensionality(self, w: CoordT) -> None:
        """Test `~galax.coordinates.AbstractPhaseSpaceCoordinate.dimensionality`."""
        assert w._dimensionality() == 7

    def test_data_keys(self, w: CoordT) -> None:
        """Test :attr:`~galax.coordinates.PhaseSpacePosition.data`."""
        assert isinstance(w.data, cx.KinematicSpace)

        assert "length" in w.data
        assert isinstance(w.data["length"], cx.vecs.FourVector)

        assert "speed" in w.data
        assert isinstance(w.data["speed"], cx.vecs.AbstractVel3D)

    # =========================================================
    # Array API

    # ----------------------------
    # getitem

    def test_getitem_int(self, w: CoordT) -> None:
        """Test `~galax.coordinates.AbstractPhaseSpaceCoordinate.__getitem__`."""
        assert jnp.all(w[0] == replace(w, q=w.q[0], p=w.p[0], t=w.t[0]))

    def test_getitem_slice(self, w: CoordT) -> None:
        """Test `~galax.coordinates.AbstractPhaseSpaceCoordinate.__getitem__`."""
        assert jnp.all(w[:5] == replace(w, q=w.q[:5], p=w.p[:5], t=w.t[:5]))

    def test_getitem_boolarray(self, w: CoordT) -> None:
        """Test `~galax.coordinates.AbstractPhaseSpaceCoordinate.__getitem__`."""
        idx = jnp.ones(w.q.shape, dtype=bool)
        idx = idx.at[::2].set(values=False)

        assert jnp.all(w[idx] == replace(w, q=w.q[idx], p=w.p[idx], t=w.t[idx]))

    def test_getitem_intarray(self, w: CoordT) -> None:
        """Test `~galax.coordinates.AbstractPhaseSpaceCoordinate.__getitem__`."""
        idx = jnp.asarray([0, 2, 1])
        assert jnp.all(w[idx] == replace(w, q=w.q[idx], p=w.p[idx], t=w.t[idx]))

    # ----------------------------

    def test_wt(self, w: gc.AbstractPhaseSpaceCoordinate) -> None:
        """Test :meth:`~galax.coordinates.AbstractPhaseSpaceCoordinate.wt`."""
        usys = u.unitsystems.galactic
        wt = w.wt(units=usys)
        assert wt.shape == w.full_shape
        assert jnp.array_equal(wt[..., 0], w.t.decompose(usys).value)
        assert jnp.array_equal(
            wt[..., 1:4], convert(w.q, u.Quantity).decompose(usys).value
        )
        assert jnp.array_equal(
            wt[..., 4:7], convert(w.p, u.Quantity).decompose(usys).value
        )

    # -----------------------------

    def test_uconvert(self, w: gc.AbstractPhaseSpaceCoordinate) -> None:
        """Test :meth:`~galax.coordinates.AbstractPhaseSpaceCoordinate.uconvert`."""
        w2 = w.uconvert("solarsystem")
        # TODO: more detailed tests
        assert w2.q.x.unit == "AU"
        assert w2.p.x.unit == "AU/yr"
        assert w2.t.unit == "yr"


BasicCoordT = TypeVar("BasicCoordT", bound=gc.AbstractBasicPhaseSpaceCoordinate)


class AbstractBasicPhaseSpaceCoordinate_Test(
    AbstractPhaseSpaceCoordinate_Test[BasicCoordT], metaclass=ABCMeta
):
    """Test :class:`~galax.coordinates.AbstractBasicPhaseSpaceCoordinate`."""
